# Generated by Django 3.2.9 on 2021-12-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='neigborhood',
            new_name='neighborhood',
        ),
    ]
