# Generated by Django 3.2.9 on 2022-01-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
