# Generated by Django 3.2.9 on 2022-01-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_service_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoodmember',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hood.neighborhood'),
        ),
    ]
